name: Deploy on Push
runs-on: ubuntu-latest

on: [push]
jobs:

  oxlint:
    name: es/js linter
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@0.15.3 --deny-warnings

  phpstan:
    name: phpstan
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        uses: php-actions/phpstan@v3
        with:
          path: src/ inc/

  deploy:
    name: deploy
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/projects/AutoIgnite"
