name: Deploy on Push
on: [push]
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/projects/AutoIgnite"
