name: Deploy on Push

on: [push]
jobs:

  oxlint:
    name: es/js linter

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@0.15.3 --deny-warnings

  phpstan:
    name: phpstan

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: . src

  deploy:
    name: deploy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/home/projects/AutoIgnite"
